### ISSUE TITLE
Database not found by Spark

### ISSUE THREAD

**Issue by seanjosephjurgens** [lcpilling/ukbrapR#3] opened 2024-07-23 08:58 UTC
Hi!

Thanks for this tool, that I think could be very helpful to speed up extractions on the DNAnexus RAP.
When following exactly your code in the example, I run into an error when using the `get_emr` function. This was apparent on both versions of your package; as instructed, I was running the analysis on a multi-node JupyterLab instance with Spark.

Do you have any quick fix for this?

Error message:

```
→ Connecting to Spark spark://master:41000 -- if this fails you might be on the wrong cluster/server

Check inputs
→ Checking provided codes (remember only the first 5 digits are used by UK Biobank)

 - N unique ICD10 codes: 24 
Get app database ID
 - [ app17488_20231010194301 ]
Connect Spark to this database
Error:
! org.apache.spark.sql.catalyst.analysis.NoSuchDatabaseException:
  Database 'app17488_20231010194301' not found

Run `sparklyr::spark_last_error()` to see the full Spark error (multiple lines)
To use the previous style of error message set
`options("sparklyr.simple.errors" = TRUE)`
Traceback:

1. get_emr(map_small, verbose = TRUE)
2. ukbrapR:::get_emr_spark(codes_df = codes_df, spark_master = spark_master, 
 .     verbose = verbose)
3. sparklyr::tbl_change_db(sc, app_id)
4. invoke(hive_context(sc), "sql", sql)
5. invoke.shell_jobj(hive_context(sc), "sql", sql)
6. invoke_method(spark_connection(jobj), FALSE, jobj, method, ...)
7. invoke_method.spark_shell_connection(spark_connection(jobj), 
 .     FALSE, jobj, method, ...)
8. core_invoke_method(sc, static, object, method, FALSE, ...)
9. core_invoke_method_impl(sc, static, noreply = FALSE, object, 
 .     method, return_jobj_ref, ...)
10. spark_error(msg)
11. rlang::abort(message = msg, use_cli_format = TRUE, call = NULL)
12. signal_abort(cnd, .file)
```

**Comment by lcpilling** [comment] 2024-07-23 09:43
Hi. 

This is strange - the function has found the database `app17488_20231010194301` file that exists in your project directory, but when {sparklyr} tries to connect it says the database is not found.

I expect this is because you have multiple dataset files in your project directory? By default the package uses the most recent. I just applied a quick fix so that the correct database file is identified. Can you update your installation to the development version here 0.1.6.9000 (by doing `remotes::install_github("lcpilling/ukbrapR")` again) and let me know if this fixed it for you?

Luke

**Comment by seanjosephjurgens** [comment] 2024-07-25 07:45
Hi Luke, 

Thanks! For whatever reason, our database was 'closed'. I have gone ahead and dispensed an entirely fresh UKB RAP project.

Now the function seems to be doing something, although it seems to get stuck forever at various idiosyncratic stages without ever producing output. For instance, sometimes it will be forever 'running' without streaming any messages; in most cases it will be forever 'running' after the following message: 
```
→ Checking provided codes (remember only the first 5 digits are used by UK Biobank)
```

Is this typical to be quite slow, and does Spark somehow affect message streaming (I have seen this before). Or is something going wrong? Happy to open another issue, of course. It just seems strange to me that running this on RAP, on a fresh project, with exactly your examples, yields unexepected results :(.

Any help is much appreciated!!

Thanks,
Sean

**Comment by lcpilling** [comment] 2024-07-25 08:56
Hi Sean,

I have found before that if a function is interrupted the connection to Spark can become unresponsive. Only solution I've found is to make a new Spark instance. 

If you use "verbose = TRUE" it might give us more clues where exactly the code gets to before stopping. Also, could you post the actual command you submit, the version of the package, and ideally the codes data.frame? I might then be able to help diagnose and potentially fix.

I should add that I am moving away from using the Spark version at all. It is expensive, slow, and unreliable (RE the connection issue above, and reliable on "high priority" nodes). I am part way through changing the package to put much greater emphasis on non-Spark requirements. The recent announcement that we **must** use the RAP for all new analysis means I want to make the package faster/cheaper so this means non-Spark environments (they are 10% the cost and you get to use RStudio, yay!). The only downside is you require intermediate files. But this is actually fairly trivial to just keep the exported raw UK Biobank data (i.e., any modification to raw fields is still done in the analysis script and is therefore entirely reproducible). So I am not planning on any updates to the Spark functions other than bug fixes.

Luke

**Comment by seanjosephjurgens** [comment] 2024-07-25 09:06
Luke,

It sounds like a fantastic plan to have the code updated to work outside of Spark! Do let me know once you have an updated version. When is it expected?

Thanks a lot,
Sean

**Comment by lcpilling** [comment] 2024-07-25 09:26
Some of the functions are available in the branch already: https://github.com/lcpilling/ukbrapR/tree/exported_files

If you install this branch in a "normal" priorty instance using RStudio `remotes::install_github("lcpilling/ukbrapR@exported_files")`

Then run `ukbrapR::export_tables()` this will submit the required table-exporter commands to save the ~10Gb of raw text files required (this costs ~£0.15 per month to store in the RAP space). Terminate the RStudio session until they're all saved. After ~15mins they will be available in the RAP persistent storage. 

Launch a new RStudio (so that the files can be seen) and you can use `ukbrapR::get_diagnoses()` just like you used `ukbrapR::get_emr()` before, but now it will use the exported text files. I've also added searches to the operations and cancer registry data.

This is as far as I have got... the `ukbrapR::get_df()` function to get date first diagnoses from any source is not yet finished. And not much of the documentation is consistent yet! If you happen to try these out that would be useful, and report any issues.

Hopefully in the next few weeks I will finish!

Thanks,
Luke

**Comment by seanjosephjurgens** [comment] 2024-07-25 09:30
This is already of great help, thanks!!

**Comment by lcpilling** [comment] 2024-07-30 12:10
Hi @seanjosephjurgens - I have completed the recent update to v0.2.0 so am going to close this issue. If you are still having problems then feel free to re-open or create a new issue

**Closed as completed by lcpilling** 2024-07-30 12:10 UTC
